/*rel-viewer Event Definitions*/
var EVENT_MOUSEIN 			= 0;
var EVENT_MOUSEOUT 			= 1;
var EVENT_SELECTIONCHANGED	= 2;
var EVENT_CLICK 			= 3;
var EVENT_DOUBLECLICK 		= 4;
var EVENT_CONTEXTMENU 		= 5;
var EVENT_MENU_COMMAND 		= 6;
var EVENT_FILEDONE 			= 7;	
var EVENT_LAYOUTDONE	 	= 8;